name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Enable Cloud Run API
        run: gcloud services enable run.googleapis.com
      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/ai-calambury --dockerfile=docker/Dockerfile .
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ai-calambury \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/ai-calambury \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated
